package com.rplbo.app.services;

import com.rplbo.app.db.DBConnection;
import com.rplbo.app.models.ECommerceItem;
import com.rplbo.app.models.Item;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class OmniSyncService {

    public void syncStockToAllPlatforms(Item item) {
        System.out.println("🔄 OmniSync: Menjalankan sinkronisasi global untuk " + item.getName());

        DBConnection db = DBConnection.getInstance();

        // 1. Ambil semua platform E-Commerce yang terdaftar di database
        List<Map<String, Object>> allPlatforms = db.selectAll("ecommerces");

        for (Map<String, Object> platformRow : allPlatforms) {
            int ecomId = ((Number) platformRow.get("ecom_id")).intValue();
            String ecomName = (String) platformRow.get("ecom_name");

            // 2. Cek apakah barang ini sudah terdaftar di platform tersebut
            String checkSql = "SELECT * FROM ecommerce_items WHERE item_id = ? AND ecom_id = ?";
            List<Map<String, Object>> existingListing = db.selectAllCustom(checkSql, item.getId(), ecomId);

            ECommerceItem listing;

            if (existingListing == null || existingListing.isEmpty()) {
                // --- LOGIKA AUTO-LISTING ---
                System.out.println("➕ Auto-Listing: Mendaftarkan " + item.getName() + " ke " + ecomName);

                // Buat listing baru dengan harga default
                listing = new ECommerceItem(item.getId(), ecomId, item.getSellingPrice());

                // Buat ID Listing Simulasi (Karena belum pakai API asli)
                String autoGeneratedId = ecomName.substring(0, 3).toUpperCase() + "-" + System.nanoTime() % 10000;

                // Gunakan Map sementara untuk set data yang belum ada di constructor
                Map<String, Object> dataMap = listing.toMap();
                dataMap.put("external_listing_id", autoGeneratedId);
                dataMap.put("synced_stock", item.getStock());
                dataMap.put("sync_status", "SYNCED");

                // Simpan baris baru ke database
                db.insertIntoTable("ecommerce_items", dataMap);

                // Refresh objek agar mendapatkan ID dari DB
                Map<String, Object> savedRow = db.fetchRow("ecommerce_items", "external_listing_id", autoGeneratedId);
                listing = new ECommerceItem(savedRow);

            } else {
                // --- LOGIKA SYNC BIASA ---
                listing = new ECommerceItem(existingListing.get(0));
            }

            // 3. Eksekusi Simulasi Push Cloud
            System.out.println("☁️ Pushing stock " + item.getStock() + " ke Listing: " + listing.getExternalListingId() + " (" + ecomName + ")");

            // 4. Update status sinkronisasi terakhir di local DB
            listing.markSynced(item.getStock());
        }

        System.out.println("✅ Semua platform (" + allPlatforms.size() + ") sudah tersinkronisasi.");
    }
}